language: python

python:
    - "2.7"

install:
    - pip install -r requirements.txt

script:
    - python -c 'import networkx; print(networkx.__version__);'
    - make test
    - python setup.py test
